# Site settings
title: FITE Club
email: register@fiteclub.org
url: http://fiteclub.org
description: "FITE Club - Financial Innovation Technology Events"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Chris Swan
  location: London

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Credits content
credits: 'Based on <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer</a>, a free to use, open source Bootstrap theme.'

# Build settings
markdown: kramdown
permalink: pretty
